version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

    commands:
      - n lts

  build:
    commands:
      - npm install -g yarn
      - yarn
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
